FROM python:3.12-slim

# Install system dependencies for Poppler (pdftoppm)
RUN apt-get update && apt-get install -y \
    poppler-utils \
    && rm -rf /var/lib/apt/lists/*

# Install uv.
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

# Copy the application into the container.
COPY . /app

# Install the application dependencies.
WORKDIR /app
RUN uv sync --frozen --no-cache

# Run Celery Worker
CMD ["/app/.venv/bin/celery", "-A", "src.workers.celery", "worker", "-E", "--loglevel=info"]