import os

SUPABASE_URL = os.getenv('SUPABASE_URL')
SUPABASE_SECRET_KEY = os.getenv('SUPABASE_SECRET_KEY')
SUPABASE_JWT_SECRET = os.getenv('SUPABASE_JWT_SECRET')

CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND')

OPENAI_API_KEY = os.getenv('OPENAI_API_KEY')

APOLLO_API_KEY = os.getenv('APOLLO_API_KEY')

ASHBY_API_KEY = os.getenv('ASHBY_API_KEY')
FATHOM_API_KEY = os.getenv('FATHOM_API_KEY')

EMAIL_HOSTNAME = os.getenv('EMAIL_HOSTNAME')
EMAIL_PORT = os.getenv('EMAIL_PORT')
EMAIL_USERNAME = os.getenv('EMAIL_USERNAME')
EMAIL_PASSWORD = os.getenv('EMAIL_PASSWORD')

LEMLIST_API_KEY = os.getenv('LEMLIST_API_KEY')